#!/bin/bash
pacman -Qei | awk '/^Name/ { name=$3 } /^Groups/ { if ( $3 != "base" && $3 != "base-devel" && $3 != "xorg" && $3 != "xorg-apps" && $3 != "xorg-fonts" && $3 != "vulkan-devel" && $3 != "qt") { print name } }'
